name: FreeBSD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Zed on FreeBSD
    # env:
    #   MYTOKEN : ${{ secrets.MYTOKEN }}
    #   MYTOKEN2: "value2"
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@c3ae29a132c8ef1924775414107a97cac042aad5 # v1.2.0
        with:
          # envs: "MYTOKEN MYTOKEN2"
          usesh: true
          release: 13.5
          copyback: true
          prepare: |
            pkg install -y \
              curl git rustup-init cmake-core llvm-devel-lite pkgconf protobuf # ibx11 alsa-lib rust-bindgen-cli
          run: |
            freebsd-version
            sysctl hw.model
            sysctl hw.ncpu
            sysctl hw.physmem
            sysctl hw.usermem
            rustup-init --profile minimal --default-toolchain none -y
            . "$HOME/.cargo/env"
            cargo build -p remote_server
            target/debug/remote_server version
            mkdir -p out/
            cp target/debug/remote_server out/
            cargo clean
      - name: Look around
        run: |
          ls -la out/
          file out/remote_server/
